import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/hooks/userSidebar";
 import {ThemeProvider} from "@/hooks/userTheme";
 
import { Box, CssBaseline } from "@mui/material";
import "./globals.css";
import { Sidebar } from "@/shared/layout/Sidebar";
import Header  from "@/shared/layout/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Your App Name",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SidebarProvider>
          <ThemeProvider>
          <CssBaseline />
          <Box sx={{ display: "flex", minHeight: "100vh" }}>
            <Sidebar />
            <Header/>
           <Box
  component="main"
  sx={{
    flexGrow: 1,
    p: 3,
    bgcolor: "background.default",  // uses MUI theme key (will be correct in Client Components)
    color: "text.primary",
    width: "100%",
  }}
>
  {children}
</Box>

          </Box>
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
